--Author Evseev V.
--Comment Создание таблицы "Производители"
--Since 24.12.2016
CREATE TABLE IF NOT EXISTS SHOP.PRODUCERS (
  ID INTEGER NOT NULL IDENTITY,
  NAME VARCHAR(2000) NOT NULL,
  COUNTRY VARCHAR (150) NOT NULL,

  PRIMARY KEY (ID)
);

--Author Evseev V.
--Comment Создание таблицы "Категории товаров"
--Since 24.12.2016
CREATE TABLE IF NOT EXISTS SHOP.CATEGORIES (
  ID INTEGER NOT NULL IDENTITY,
  NAME VARCHAR(2000) NOT NULL,

  PRIMARY KEY (ID)
);

--Author Evseev V.
--Comment Создание таблицы "Поставщики"
--Since 24.12.2016
CREATE TABLE IF NOT EXISTS SHOP.PROVIDERS (
  ID INTEGER NOT NULL IDENTITY,
  ADRESS VARCHAR(360) NOT NULL,
  NAME VARCHAR(2000) NOT NULL,
  CONTACT VARCHAR(2000),

  PRIMARY KEY (ID)
);

--Author Evseev V.
--Comment Создание таблицы "Товары"
--Since 24.12.2016
CREATE TABLE IF NOT EXISTS SHOP.PRODUCTS (
  ID INTEGER NOT NULL IDENTITY,
  CODE VARCHAR(36) NOT NULL,
  NAME VARCHAR(2000) NOT NULL,
  PROVIDER_ID INTEGER,
  CATEGORY_ID INTEGER,
  QUANTITY INTEGER NOT NULL DEFAULT 0,
  PRICE DECIMAL(7, 2) NOT NULL,
  PRODUCER_ID INTEGER,

  PRIMARY KEY (ID),
  FOREIGN KEY (PROVIDER_ID) REFERENCES SHOP.PROVIDERS (ID) ON UPDATE CASCADE,
  FOREIGN KEY (CATEGORY_ID) REFERENCES SHOP.CATEGORIES (ID) ON UPDATE CASCADE,
  FOREIGN KEY (PRODUCER_ID) REFERENCES SHOP.PRODUCERS (ID) ON UPDATE CASCADE
);

--Author Evseev V.
--Comment Создание таблицы "Клиенты"
--Since 24.12.2016
CREATE TABLE IF NOT EXISTS SHOP.CLIENTS (
  ID INTEGER NOT NULL IDENTITY,
  NAME VARCHAR(250) NOT NULL,
  ADRESS VARCHAR(250) NOT NULL,
  PHONE VARCHAR(250),
  EMAIL VARCHAR(250),

  PRIMARY KEY (ID)
);

--Author Evseev V.
--Comment Создание таблицы "Заказы"
--Since 24.12.2016
CREATE TABLE IF NOT EXISTS SHOP.ORDERS (
  ID INTEGER NOT NULL IDENTITY,
  CLIENT_ID INTEGER NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  QUANTITY INTEGER NOT NULL DEFAULT 0,
  AMOUNT DECIMAL(7, 2) NOT NULL,
  STATUS VARCHAR (12) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES SHOP.CLIENTS (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES SHOP.PRODUCTS (ID)
);